# Generated by Django 2.0.9 on 2019-07-04 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('oidc_provider', '0026_client_multiple_response_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='JWTToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expires_at', models.DateTimeField(verbose_name='Expiration Date')),
                ('_scope', models.TextField(default='', verbose_name='Scopes')),
                ('refresh_token', models.CharField(max_length=255, unique=True, verbose_name='Refresh Token')),
                ('_id_token', models.TextField(verbose_name='ID Token')),
                ('access_token', models.TextField(max_length=65000, verbose_name='Access Token')),
                ('access_token_hash', models.CharField(max_length=255, unique=True, verbose_name='Access Token Hash')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oidc_provider.Client', verbose_name='Client')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Token',
                'verbose_name_plural': 'Tokens',
            },
        ),
    ]
