# Generated by Django 2.0.9 on 2019-07-26 11:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('oidc_provider', '0027_jwttoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='jwttoken',
            name='jti',
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
    ]
