# Generated by Django 2.0.9 on 2020-03-12 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oidc_provider', '0029_auto_20200310_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='code_expire',
            field=models.IntegerField(default=600),
        ),
        migrations.AddField(
            model_name='client',
            name='idtoken_expire',
            field=models.IntegerField(default=600),
        ),
        migrations.AddField(
            model_name='client',
            name='token_expire',
            field=models.IntegerField(default=3600),
        ),
    ]
