# Generated by Django 2.0.9 on 2020-03-25 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0025_remove_userdomain_clients'),
        ('oidc_provider', '0030_auto_20200312_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='user_domain',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='identity.UserDomain'),
        ),
    ]
